/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.City;
import BL.Country;
import BL.Event;
import BL.EventLocation;
import DAL.CityException;
import DAL.CityInterface;
import DAL.CityRepository;
import DAL.CountryInterface;
import DAL.CountryRepository;
import DAL.EventInterface;
import DAL.EventLocationException;
import DAL.EventLocationInterface;
import DAL.EventLocationRepository;
import DAL.EventRepository;
import Model.CityComboBoxModel;
import Model.CountryComboBoxModel;
import Model.EventComboBoxModel;
import Model.EventLocationModel;
import com.sun.glass.events.KeyEvent;
import static java.lang.Character.isAlphabetic;
import static java.lang.Character.isDigit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author dell
 */
public class EventLocationForm extends javax.swing.JInternalFrame {

     EventLocationRepository eventLocationRepository = new EventLocationRepository();
     EventLocationInterface eventLocationI = new EventLocationRepository();
     EventLocationModel eventLocationModel = new EventLocationModel();
     EventInterface eventI = new EventRepository();
     CityInterface cityR = new CityRepository();
     CountryInterface countryR = new CountryRepository();
     CountryComboBoxModel cmbM;
     CityComboBoxModel cityCM;
     EventComboBoxModel eventCM;
     
    
    
    
    
    public EventLocationForm() {
        initComponents();
        tabelaLoad();
        countryCombo();
        eventCombo();
        emptyObject();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LocationTable = new javax.swing.JTable();
        lblStreet = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCName = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        CityCombo = new javax.swing.JComboBox<>();
        CountryCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        EventCombo = new javax.swing.JComboBox<>();
        lblCountry = new javax.swing.JLabel();

        setClosable(true);
        setForeground(new java.awt.Color(255, 0, 0));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Save-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Close-2-icon delete.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Actions-edit-redo-icon.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("       Country : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("      City : ");

        txtStreet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStreetKeyPressed(evt);
            }
        });

        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("  Street  : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Description");

        LocationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(LocationTable);

        lblStreet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStreet.setForeground(new java.awt.Color(255, 0, 0));

        lblDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 0, 0));

        lblCName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCName.setForeground(new java.awt.Color(255, 51, 51));

        lblEvent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEvent.setForeground(new java.awt.Color(255, 0, 0));

        CityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityComboActionPerformed(evt);
            }
        });

        CountryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("    Event : ");

        lblCountry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(255, 0, 0));
        lblCountry.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CountryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(lblStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblCName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EventCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void countryCombo()
    {
        List<Country> cList = countryR.findAllOrdered();
        cmbM = new CountryComboBoxModel(cList);
        this.CountryCombo.setModel(cmbM);
        
    }
    
    public void addToCityCombo(Country country)
    {
        List<City> cList = cityR.findCitys(country);
        cityCM = new CityComboBoxModel(cList);
        this.CityCombo.setModel(cityCM);
        
    }
    
    public void eventCombo()
    {
        List<Event> cList = eventI.findAll();
        eventCM = new EventComboBoxModel(cList);
        this.EventCombo.setModel(eventCM);
        
    }
    
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try {
            
            
            int row = LocationTable.getSelectedRow();
            if (txtStreet.getText().equals("") ||txtDescription.getText().equals("") 
                    || CountryCombo.getSelectedItem() == null || CityCombo.getSelectedItem() == null
                    || EventCombo.getSelectedItem() == null )
            {
                JOptionPane.showMessageDialog(this, "Ju lutem Mbusheni gjitha kolonat :", "Error", JOptionPane.ERROR_MESSAGE);
                if(CountryCombo.getSelectedItem() == null )
                    lblCountry.setText( " Selekto nje shtet ! ");
                if(CityCombo.getSelectedItem() == null )
                    lblCName.setText(" Selekto nje Qytet ");
                if(EventCombo.getSelectedItem() == null ) 
                    lblEvent.setText(" Selekto nje Event ! ");
                if(txtStreet.getText().equals(""))
                    lblStreet.setText(" Mbyshni te dhenat e Rruges ! ");
                if(txtDescription.getText().equals(""))
                    lblDescription.setText(" Shkruani te dhena ne fushen Description ! ");
                    
                    
                
            } 
            else{
                lblCountry.setText( "");
                lblCName.setText("");
                lblEvent.setText("");
                lblStreet.setText("");
                lblDescription.setText("");
               
                if(row == -1)
                {
                    Event event = eventI.findById(3);
                    EventLocation eventLocation = new EventLocation();
                    City city = (City)CityCombo.getSelectedItem();
                     eventLocation.setCityID(city);
                     eventLocation.setCityID(city);
                     eventLocation.setEventID(event);
                    
                    
                    
                    
                    eventLocation.setStreet(txtStreet.getText());
                    eventLocation.setDescription(txtDescription.getText());
                    

                    eventLocationRepository.create(eventLocation);
                    
                    
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses !");
                } 
                else 
                {
                    EventLocation eventLocation = this.eventLocationModel.getEventLocation(row);
                    
                    Event event = (Event) EventCombo.getSelectedItem();
                    
                    City city = (City)CityCombo.getSelectedItem();
                    eventLocation.setCityID(city);
                    eventLocation.setEventID(event);
                    
                    
                    eventLocation.setStreet(txtStreet.getText());
                    eventLocation.setDescription(txtDescription.getText());
                    
                    
                    
                    
                    eventLocationRepository.edit(eventLocation);
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses");
                }
                emptyObject();
                tabelaLoad();
            }
              
        }   catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        emptyObject();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        try{
            
            
            int row = LocationTable.getSelectedRow();
            if(row > -1){
                Object [] ob = {"Po","Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if(i==0){
                    EventLocation eventLocation = this.eventLocationModel.getEventLocation(row);

                    eventLocationRepository.remove(eventLocation);

                 
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Nuk keni selektuar asgjë për të fshir !");
            }
         
         } catch (EventLocationException ex) {
             ex.printStackTrace();
         }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyPressed
        
        
        char c = evt.getKeyChar();
        if(isAlphabetic(c) || c == KeyEvent.VK_BACKSPACE || evt.isControlDown() || evt.isShiftDown())
        {
            txtDescription.setEditable(true);
            lblDescription.setText("");
            
         }
        else
        { 
            txtDescription.setEditable(false);
            lblDescription.setText("Nuk duhet te shtypen numra !");
        }
    }//GEN-LAST:event_txtDescriptionKeyPressed

    private void txtStreetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStreetKeyPressed
        
        char c = evt.getKeyChar();
        if(isAlphabetic(c) || c == KeyEvent.VK_BACKSPACE || evt.isControlDown() || evt.isShiftDown())
        {
            txtStreet.setEditable(true);
            lblStreet.setText("");
            
         }
        else
        { 
            txtStreet.setEditable(false);
            lblStreet.setText("Rruga eshte dhene gabim !");
        }
    }//GEN-LAST:event_txtStreetKeyPressed

    private void CityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CityComboActionPerformed

    private void CountryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryComboActionPerformed
        // TODO add your handling code here:
        
        Country country = (Country)CountryCombo.getSelectedItem();
        addToCityCombo(country);
    }//GEN-LAST:event_CountryComboActionPerformed

    private void tabelaLoad() {
        List<EventLocation> lista = eventLocationRepository.findAll();
        eventLocationModel.add(lista);
        LocationTable.setModel(eventLocationModel);
        eventLocationModel.fireTableDataChanged();
        tabelaSelectedIndexChange();
    
    }
    
    private void tabelaSelectedIndexChange(){
        final ListSelectionModel rowSM = LocationTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    
                    EventLocation eventLocation = eventLocationModel.getEventLocation(selectedIndex);
                    City city = (City)eventLocation.getCityID();
                    Event event = (Event)eventLocation.getEventID();
                    
                    txtStreet.setText(eventLocation.getStreet());
                    txtDescription.setText(eventLocation.getDescription());
                    
                    
                    
                    CountryCombo.setSelectedItem(city.getCountryID());
                    CountryCombo.repaint();
                    
                    CityCombo.setSelectedItem(city);
                    CityCombo.repaint();
                   
                    EventCombo.setSelectedItem(event);
                    EventCombo.repaint();
                    
                    
                }
            }
        });
    }
    
    
    public void emptyObject()
    {
        LocationTable.clearSelection();
        CountryCombo.setSelectedItem(null);
        CityCombo.setSelectedItem(null);
        EventCombo.setSelectedItem(null);
        txtStreet.setText("");
        txtDescription.setText("");
        
        
    }
    
    
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<City> CityCombo;
    private javax.swing.JComboBox<Country> CountryCombo;
    private javax.swing.JComboBox<Event> EventCombo;
    private javax.swing.JTable LocationTable;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
