/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author darda
 */
public class MainAplicationForm extends javax.swing.JFrame {

    /**
     * Creates new form MainAplicationForm1
     */
    public MainAplicationForm() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);

        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addUser = new javax.swing.JMenuItem();
        addRole = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addCountry = new javax.swing.JMenuItem();
        addCity = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AddCategory = new javax.swing.JMenuItem();
        addSubCategory = new javax.swing.JMenuItem();
        addEvent = new javax.swing.JMenuItem();
        addSponsor = new javax.swing.JMenuItem();
        addEventLocation = new javax.swing.JMenuItem();
        addEntryType = new javax.swing.JMenuItem();
        Gjenero = new javax.swing.JMenu();
        btnGjeneroEP = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jMenu1.setText("User");

        addUser.setMnemonic('o');
        addUser.setText("Add User");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        jMenu1.add(addUser);

        addRole.setText("Add Role");
        addRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoleActionPerformed(evt);
            }
        });
        jMenu1.add(addRole);

        menuBar.add(jMenu1);

        jMenu2.setText("Location");

        addCountry.setMnemonic('s');
        addCountry.setText("Add Country");
        addCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCountryActionPerformed(evt);
            }
        });
        jMenu2.add(addCountry);

        addCity.setMnemonic('a');
        addCity.setText("Add City");
        addCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCityActionPerformed(evt);
            }
        });
        jMenu2.add(addCity);

        menuBar.add(jMenu2);

        jMenu3.setText("Event");

        AddCategory.setMnemonic('x');
        AddCategory.setText("Add Event Category");
        AddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCategoryActionPerformed(evt);
            }
        });
        jMenu3.add(AddCategory);

        addSubCategory.setText("Add Sub Category");
        addSubCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubCategoryActionPerformed(evt);
            }
        });
        jMenu3.add(addSubCategory);

        addEvent.setText("Add Event");
        addEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventActionPerformed(evt);
            }
        });
        jMenu3.add(addEvent);

        addSponsor.setText("Add Sponsor");
        addSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSponsorActionPerformed(evt);
            }
        });
        jMenu3.add(addSponsor);

        addEventLocation.setText("Add Event Location");
        addEventLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventLocationActionPerformed(evt);
            }
        });
        jMenu3.add(addEventLocation);

        addEntryType.setText("Add Entry Type");
        addEntryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryTypeActionPerformed(evt);
            }
        });
        jMenu3.add(addEntryType);

        menuBar.add(jMenu3);

        Gjenero.setText("Gjener");

        btnGjeneroEP.setText("Gjenero Event/User");
        btnGjeneroEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGjeneroEPActionPerformed(evt);
            }
        });
        Gjenero.add(btnGjeneroEP);

        menuBar.add(Gjenero);

        jMenu4.setText("Back");

        jMenuItem1.setText("Back to Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCategoryActionPerformed
       EventCategoryForm ec = new EventCategoryForm();
        DesktopPane.add(ec);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = ec.getSize();
        ec.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        ec.show();
    }//GEN-LAST:event_AddCategoryActionPerformed

    private void addSubCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubCategoryActionPerformed
        SubCategoryForm sb = new SubCategoryForm();
        
        DesktopPane.add(sb);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = sb.getSize();
        sb.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        sb.show();
    }//GEN-LAST:event_addSubCategoryActionPerformed

    private void addCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCityActionPerformed
        
        CityForm lc = new CityForm();
        DesktopPane.add(lc);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = lc.getSize();
        lc.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        lc.show();

    }//GEN-LAST:event_addCityActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        UserForm user = new UserForm();
        DesktopPane.add(user);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = user.getSize();
        user.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        user.show();
        
    }//GEN-LAST:event_addUserActionPerformed

    private void addCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCountryActionPerformed
        CountryForm lc = new CountryForm();
        DesktopPane.add(lc);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = lc.getSize();
        lc.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        lc.show();
    }//GEN-LAST:event_addCountryActionPerformed

    private void addSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSponsorActionPerformed
        SponsorForm lc = new SponsorForm();
        DesktopPane.add(lc);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = lc.getSize();
        lc.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        lc.show();
    }//GEN-LAST:event_addSponsorActionPerformed

    private void addEntryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryTypeActionPerformed
        EventType et = new EventType();
        DesktopPane.add(et);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = et.getSize();
        et.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        et.show();
    }//GEN-LAST:event_addEntryTypeActionPerformed

    private void addEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventActionPerformed
        EventForm e = new EventForm();
        DesktopPane.add(e);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = e.getSize();
        e.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        e.show();
    }//GEN-LAST:event_addEventActionPerformed

    private void addRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoleActionPerformed
        RoleForm r = new RoleForm();
        DesktopPane.add(r);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = r.getSize();
        r.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        r.show();
    }//GEN-LAST:event_addRoleActionPerformed

    private void addEventLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventLocationActionPerformed
        EventLocationForm a = new EventLocationForm();
        DesktopPane.add(a);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = a.getSize();
        a.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        a.show();
                
    }//GEN-LAST:event_addEventLocationActionPerformed

    private void btnGjeneroEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGjeneroEPActionPerformed
        GjeneroEventUser ev = new GjeneroEventUser();
        DesktopPane.add(ev);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = ev.getSize();
        ev.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        ev.show();
    }//GEN-LAST:event_btnGjeneroEPActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension evSize = l.getSize();
        l.setLocation((desktopSize.width - evSize.width)/2,
        (desktopSize.height- evSize.height)/2);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       Object [] ob = {"Po","Jo"};
        int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta dilni ?", "Fshirja", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
        if(i == 0)
        {
            System.exit(0);
            
        }
            
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAplicationForm().setVisible(true);    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddCategory;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu Gjenero;
    private javax.swing.JMenuItem addCity;
    private javax.swing.JMenuItem addCountry;
    private javax.swing.JMenuItem addEntryType;
    private javax.swing.JMenuItem addEvent;
    private javax.swing.JMenuItem addEventLocation;
    private javax.swing.JMenuItem addRole;
    private javax.swing.JMenuItem addSponsor;
    private javax.swing.JMenuItem addSubCategory;
    private javax.swing.JMenuItem addUser;
    private javax.swing.JMenuItem btnGjeneroEP;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
