

package GUI;


import EVPS.WriteInNote;
import EVPS.WriteInNoteException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author darda
 */
public class WriteIn extends javax.swing.JInternalFrame {

    
    
    public WriteIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWrite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        btnSelectL = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnWrite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnWrite.setText("Write");

        txtText.setColumns(20);
        txtText.setRows(5);
        jScrollPane1.setViewportView(txtText);

        btnSelectL.setText("Select Location");
        btnSelectL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnWrite)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(btnSelectL)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnSelectL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnWrite)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLActionPerformed
        try
        {
            WriteInNote wN;
            JFileChooser jc = new JFileChooser();
            jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int res = jc.showOpenDialog(this);
            if(res == JFileChooser.APPROVE_OPTION)
            {
                if(!(jc.getSelectedFile().isDirectory()))
                    JOptionPane.showMessageDialog(this, "Ju lutem selektoni nje folder","Error",JOptionPane.ERROR_MESSAGE);
                else
                {
                    String path = jc.getSelectedFile().getPath()+"\\netbeans.txt\\";
                    wN = new WriteInNote(txtText.getText(),path);
                    wN.write();
                }

            }else
            {
                JOptionPane.showMessageDialog(this, "Ju lutem selektoni nje folder","Error",JOptionPane.ERROR_MESSAGE);
            }
        }catch(WriteInNoteException | IOException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSelectLActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectL;
    private javax.swing.JButton btnWrite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
